replicaCount: 2

image:
  repository: microgitops
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "traefik"
  host: "microgitops.duckdns.org"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

serviceMonitor:
  enabled: false
  interval: 15s
  path: /metrics
